name: clarity_break
description: "Cannabis tolerance break tracker"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state & storage
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0

  # UI & theming
  intl: ^0.18.1
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.7
  another_flutter_splash_screen: ^1.2.1
  confetti: ^0.7.0
  smooth_page_indicator: ^1.0.0

  # charts
  fl_chart: ^0.55.2

  # timezones for notifications
  timezone: ^0.9.4

  # sharing & file I/O
  share_plus: ^11.0.0
  file_selector: ^0.9.2
  path_provider: ^2.0.14

  # misc
  uuid: ^3.0.6
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # icon & splash generators
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.2.17

# flutter_launcher_icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

# flutter_native_splash configuration
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/data/library_content.json
    - assets/images/empty_journal.png
    - assets/images/empty_history.png
    - assets/images/home_inactive_graphic.png
